### ISSUE TITLE
提供的示例里“重阳”拼音有问题

### ISSUE THREAD

**Issue by JianleiZhang** [struCoder/Go-pinyin#10]
pinyingo.NewPy(pinyingo.STYLE_INITIALS, pinyingo.USE_SEGMENT) 只显示 [ch ]
pinyingo.NewPy(pinyingo.STYLE_FIRST_LETTER, pinyingo.USE_SEGMENT) 则为 [ ]

**Comment by struCoder** [comment]
你好，感谢你的反馈，
1. 在INITIALS(声母)模式下是没有y, w, yu几个声母
声母风格（INITIALS）下，“雨”、“我”、“圆”等汉字返回空字符串，因为根据《汉语拼音方案》， y，w，ü (yu) 都不是声母，在某些特定韵母无声母时，才加上 y 或 w，而 ü 也有其特定规则。
2. STYLE_FIRST_LETTER已经修复。以下是最新的测试
![image](https://cloud.githubusercontent.com/assets/6498477/25326140/622256f8-2901-11e7-907f-cd30331743c6.png)
