### ISSUE TITLE
使用go.mod的用户伤不起啊！

### ISSUE THREAD

**Issue by yuqisse** [struCoder/Go-pinyin#13]
![image](https://user-images.githubusercontent.com/46594112/55667540-11e0f080-5890-11e9-827f-a19d2957db17.png)
开启go module后依赖包下载到了$GOPATH/pkg/mod目录下，这个目录失效了。为此怀疑人生了很久，以为是我的go11没有依赖到mod下的包

**Comment by struCoder** [comment]
@yuqisse 
哈哈，目前你还是第一个反馈这个问题的。目测绝大多数用户还是用的传统包依赖。
你可以修改源代码后重新编译，或者考虑一个兼容方案发一个PR。欢迎哦 💯
