### ISSUE TITLE
翻译汉字 "呗" 的时候报错

### ISSUE THREAD

**Issue by WQG6848** [struCoder/Go-pinyin#8]
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x4357560, 0xc42000c100)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
github.com/struCoder/Go-pinyin.normalStr(0x437627f, 0x3, 0x4373156, 0x1)
	/Users/wings/Go/src/github.com/struCoder/Go-pinyin/tools.go:81 +0x15e
github.com/struCoder/Go-pinyin.(*options).perStr(0xc4207edef0, 0x437627f, 0x8, 0x3, 0x3)
	/Users/wings/Go/src/github.com/struCoder/Go-pinyin/convert.go:28 +0x194
github.com/struCoder/Go-pinyin.(*options).doConvert(0xc4207edef0, 0x4373699, 0x3, 0x4454da8, 0x0, 0x0)
	/Users/wings/Go/src/github.com/struCoder/Go-pinyin/convert.go:53 +0x265
github.com/struCoder/Go-pinyin.(*options).Convert(0xc4207edef0, 0x4373699, 0x3, 0x0, 0x434e160, 0x30d40)
	/Users/wings/Go/src/github.com/struCoder/Go-pinyin/convert.go:81 +0x4d8
main.main()
	/Users/wings/Desktop/goNote/test/pinyin.go:12 +0x77

代码如下：

func main() {
	str := "呗"
	py := pinyingo.NewPy(pinyingo.STYLE_NORMAL, pinyingo.NO_SEGMENT)
	pin := py.Convert(str)
	fmt.Println(pin, len(pin))
}

**Comment by struCoder** [comment]
@WQG6848 
你好，多谢反馈，导致这个的原因是*呗*这个汉字没有音调和韵母。已经fixed
